[project]
name = "flaskwebstudy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask-migrate>=4.1.0",
    "flask-sqlalchemy>=3.1.1",
    "flask[async]>=3.1.2",
    "mysqlclient>=2.2.7",
    "watch>=0.2.7",
]
